CREATE TABLE IF NOT EXISTS `venda` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`descricao` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_0900_ai_ci',
	`dtvenda` DATETIME NULL DEFAULT NULL,
	`pagamento` INT(10) NOT NULL DEFAULT '0',
	`totalvenda` DOUBLE NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
